export const PERMISSIONS = {
  STUDENT_VIEW: "STUDENT_VIEW",
  STUDENT_CREATE: "STUDENT_CREATE",
  STUDENT_EDIT: "STUDENT_EDIT",
  STUDENT_SUSPEND: "STUDENT_SUSPEND",

  AGENT_VIEW: "AGENT_VIEW",
  AGENT_CREATE: "AGENT_CREATE",
  AGENT_EDIT: "AGENT_EDIT",
  AGENT_APPROVE: "AGENT_APPROVE",
  AGENT_SUSPEND: "AGENT_SUSPEND",

  DOCUMENT_VIEW: "DOCUMENT_VIEW",
  DOCUMENT_APPROVE: "DOCUMENT_APPROVE",
  DOCUMENT_REJECT: "DOCUMENT_REJECT",

  PLACEMENT_VIEW: "PLACEMENT_VIEW",
  PLACEMENT_CREATE: "PLACEMENT_CREATE",
  PLACEMENT_EDIT: "PLACEMENT_EDIT",
  PLACEMENT_ASSIGN: "PLACEMENT_ASSIGN",
  PLACEMENT_CONFIRM: "PLACEMENT_CONFIRM",

  PAYMENT_VIEW: "PAYMENT_VIEW",
  PAYMENT_VERIFY: "PAYMENT_VERIFY",
  PAYMENT_REFUND: "PAYMENT_REFUND",

  COMMISSION_VIEW: "COMMISSION_VIEW",
  COMMISSION_APPROVE: "COMMISSION_APPROVE",

  WITHDRAWAL_VIEW: "WITHDRAWAL_VIEW",
  WITHDRAWAL_APPROVE: "WITHDRAWAL_APPROVE",
  WITHDRAWAL_REJECT: "WITHDRAWAL_REJECT",

  ORGANIZATION_VIEW: "ORGANIZATION_VIEW",
  ORGANIZATION_CREATE: "ORGANIZATION_CREATE",
  ORGANIZATION_EDIT: "ORGANIZATION_EDIT",
  ORGANIZATION_SUSPEND: "ORGANIZATION_SUSPEND",

  CHAT_VIEW: "CHAT_VIEW",
  CHAT_REPLY: "CHAT_REPLY",

  REPORT_VIEW: "REPORT_VIEW",

  ADMIN_VIEW: "ADMIN_VIEW",
  ADMIN_CREATE: "ADMIN_CREATE",
  ADMIN_EDIT: "ADMIN_EDIT",
  ADMIN_DISABLE: "ADMIN_DISABLE",

  ROLE_VIEW: "ROLE_VIEW",
  ROLE_EDIT: "ROLE_EDIT",

  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
  AUDIT_LOG_VIEW: "AUDIT_LOG_VIEW",

  NOTIFICATION_CREATE: "NOTIFICATION_CREATE",
  NOTIFICATION_SEND: "NOTIFICATION_SEND",
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.PLACEMENT_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  PLACEMENT_ADMIN: [
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.PLACEMENT_VIEW,
    PERMISSIONS.PLACEMENT_CREATE,
    PERMISSIONS.PLACEMENT_EDIT,
    PERMISSIONS.PLACEMENT_ASSIGN,
    PERMISSIONS.PLACEMENT_CONFIRM,
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  DOCUMENT_ADMIN: [
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.DOCUMENT_VIEW,
    PERMISSIONS.DOCUMENT_APPROVE,
    PERMISSIONS.DOCUMENT_REJECT,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
    PERMISSIONS.REPORT_VIEW,
  ],
  FINANCE_ADMIN: [
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.PAYMENT_VERIFY,
    PERMISSIONS.PAYMENT_REFUND,
    PERMISSIONS.COMMISSION_VIEW,
    PERMISSIONS.COMMISSION_APPROVE,
    PERMISSIONS.WITHDRAWAL_VIEW,
    PERMISSIONS.WITHDRAWAL_APPROVE,
    PERMISSIONS.WITHDRAWAL_REJECT,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],
  SUPPORT_ADMIN: [
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.NOTIFICATION_CREATE,
    PERMISSIONS.NOTIFICATION_SEND,
  ],
  AGENT_MANAGER: [
    PERMISSIONS.AGENT_VIEW,
    PERMISSIONS.AGENT_CREATE,
    PERMISSIONS.AGENT_EDIT,
    PERMISSIONS.AGENT_APPROVE,
    PERMISSIONS.AGENT_SUSPEND,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
  ],
  PARTNERSHIP_ADMIN: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_CREATE,
    PERMISSIONS.ORGANIZATION_EDIT,
    PERMISSIONS.ORGANIZATION_SUSPEND,
    PERMISSIONS.PLACEMENT_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
  ],
  AGENT: [
    PERMISSIONS.STUDENT_VIEW,
    PERMISSIONS.COMMISSION_VIEW,
    PERMISSIONS.WITHDRAWAL_VIEW,
    PERMISSIONS.CHAT_VIEW,
    PERMISSIONS.CHAT_REPLY,
  ],
  STUDENT: [],
};

export function getPermissionsForRole(role: string): Permission[] {
  return ROLE_PERMISSIONS[role] || [];
}

export function hasPermission(role: string, permission: Permission): boolean {
  const perms = ROLE_PERMISSIONS[role];
  if (!perms) return false;
  return perms.includes(permission);
}
